export const TaskListArrayData = [{
    taskId: 1,
    date: "19-May-22",
    totalReportedHours: "08/08H",
    ticketList: [{
        type: "ticket",
        taskId: 1,
        ticketNo: "1",
        ticketDescription: "Ticket description goes here… this may be long text upto 250 characters",
        ticketStatus: "Completed",
        status: {},
        natureOfIssue: {},
        linkedTicket: {},
        reportedDate: "",
        respondedDate: "",
        resolvedDate: "",
        hoursSpentPlanned: "",
        hoursSpentTillDate: "",
        hoursSpentToday: "",
        remarks: "",
        priority: "Overdue",
        task: " Landing page mobile and desktop HTMLs for Employee and Manager role",
        engagement: " TataCap - IFC Tracker / Phase 1",
        plannedHours: "4.0",
        totalHours: "6.0"
    }
        , {
        type: "ticket",
        taskId: 1,
        ticketNo: "2",
        ticketDescription: "Ticket description goes here… this may be long text upto 250 characters",
        ticketStatus: "Completed",
        status: {},
        natureOfIssue: {},
        linkedTicket: {},
        reportedDate: "",
        respondedDate: "",
        resolvedDate: "",
        hoursSpentPlanned: "",
        hoursSpentTillDate: "",
        hoursSpentToday: "",
        remarks: "",
        priority: "",
        task: " Landing page mobile and desktop HTMLs for Employee and Manager role 2",
        engagement: " TataCap - IFC Tracker / Phase 2",
        plannedHours: "2.0",
        totalHours: "1.5"
    }
        , {
        type: "task",
        taskId: 1,
        ticketNo: "3",
        ticketDescription: "Ticket description goes here… this may be long text upto 250 characters",
        ticketStatus: "InProgress",
        status: {},
        natureOfIssue: {},
        linkedTicket: {},
        reportedDate: "",
        respondedDate: "",
        resolvedDate: "",
        hoursSpentPlanned: "",
        hoursSpentTillDate: "",
        hoursSpentToday: "",
        remarks: "",
        priority: "DueToday",
        task: " Landing page mobile and desktop HTMLs for Employee and Manager role 3",
        engagement: " TataCap - IFC Tracker / Phase 3",
        plannedHours: "1.0",
        totalHours: "0.5"
    }
    ]
}]